### ISSUE TITLE
Issues with file attachments

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/openelections#1003]
## Description

There are a couple of issues with the current version of file attachments on QA:

https://qa.openelectionsportland.org/contributions/1033
- [ ] Specified key does not exist error returned from https://api-qa.openelectionsportland.org/activities/1632/attachment

https://qa.openelectionsportland.org/contributions/1031
- [ ] Working attachment delivers and unspecified `attachment` with no file extension from https://api-qa.openelectionsportland.org/activities/1636/attachment

### Screen Shots

From @susanmottet:
![image](https://user-images.githubusercontent.com/7065695/70949842-bddbfd80-2013-11ea-9a83-dabce07c916e.png)

### Steps to reproduce

Visit links above

### Expected result

Should download file with proper extension.

### Actual result

See errors above

### Environment

QA, Chrome Mac OS and Windows

**Comment by danmelton** [comment]
@susanmottet @jaronheard attachments are updated on qa. Note, previous attachments may or may not work. You'll need to upload /download a new attachment to test.
