### ISSUE TITLE
Need clarity on accuracy of data

### ISSUE THREAD

**Issue by amysantee** [hackoregon/openelections#1018]
Is the data we are showing here always up-to-date? Or do we pull it every so often to update?

We want people to know how accurate it is and if there is a delay - so we should be more clear about that. There is a bit of info down at the bottom but it's easily unnoticed. 

![Screen Shot 2020-01-23 at 9 51 24 AM](https://user-images.githubusercontent.com/48701371/73009743-f6ff4e80-3dc5-11ea-9c71-8c219101930a.png)

**Comment by amysantee** [comment]
Of course, if it's always up to date, then this isn't applicable! But I recall hearing something about how it might come in waves...

**Comment by jaronheard** [comment]
This data is always up to date with the data in the Open and Accountable Elections database. This could be moved up in prominence, but I'd like to see how we're framing the product overall before making changes
