### ISSUE TITLE
Big blue circles emanating from downtown Portland is confusing

### ISSUE THREAD

**Issue by amysantee** [hackoregon/openelections#1020]
Lots of the maps have big circles coming from the downtown area. It's really confusing as to why this is the case and I think people will wonder about it. Is there any clarity and context we can provide for this?

![Screen Shot 2020-01-23 at 10 04 11 AM](https://user-images.githubusercontent.com/48701371/73010796-ed76e600-3dc7-11ea-8639-198a91f5e754.png)

**Comment by amysantee** [comment]
Remove matching contribution data from map - not necessary to show and is confusing.

**Comment by jaronheard** [comment]
@susanmottet resolved this issue on the data side. However, we still need to add a filter so that this issue doesn't recur in the future.
