### ISSUE TITLE
Remove data from OAE matching program from table

### ISSUE THREAD

**Issue by amysantee** [hackoregon/openelections#1023]
Right now we are including data from OAE matches as part of our visualizations and the table underneath the map. There is a separate ticket for the issue of the big blue circle indicating a large amount of money coming from City Hall (aka the OAE program). This ticket is regarding the table produced under each visualization, which includes a column for Large and Mega donations. These only appear because we are including OAE matching funds. Once that data is removed from our site, it should get rid of these confusing pieces of information.

![Screen Shot 2020-01-23 at 5 55 05 PM](https://user-images.githubusercontent.com/48701371/73094043-ac98d300-3e94-11ea-99f5-0c38077df598.png)

**Comment by jaronheard** [comment]
@susanmottet resolved this issue on the data side. However, we still need to add a filter so that this issue doesn't recur in the future.
