### ISSUE TITLE
Rename campaigns in production DB to candidate name

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/openelections#1030]
### What

The following campaigns need to be renamed as follows in the production DB:

| Current Name | New Name |
|--------------|----------|
| Carmen for Portland | Carmen Rubio |
| Friends of Candace Avalos | Candace Avalos |
| Friends of Seth for Portland | Seth Woolley |
| Sarah for Portland | Sarah Iannarone |
| Burleson for the People | Michael Burleson |
| Committee to Elect Tim DuBois | Tim DuBois |
| Mingus Mapps | Mingus Mapps |

### Why

In order for the data visualizations to be most useful to the public.

**Comment by jaronheard** [comment]
@andrewbiang888 Do you know if this will mess up the ORESTAR export? Does the campaign name get used or is it based on filer ID?

**Comment by andrewbiang888** [comment]
@jaronheard I'm afraid of the unknown and what this could break, but no, the export does not care about the campaign name
