### ISSUE TITLE
Design comparison interface

### ISSUE THREAD

**Issue by ghost** [hackoregon/openelections#1083]

**Comment by jaronheard** [comment]
Some early sketches on what I'm looking to implement:
[Safari - Aug 9, 2020 at 11:30 PM.pdf](https://github.com/hackoregon/openelections/files/5051831/Safari.-.Aug.9.2020.at.11.30.PM.pdf)
[Safari - Aug 9, 2020 at 11:27 PM.pdf](https://github.com/hackoregon/openelections/files/5051833/Safari.-.Aug.9.2020.at.11.27.PM.pdf)
