### ISSUE TITLE
Design unfurl

### ISSUE THREAD

**Issue by ghost** [hackoregon/openelections#1084]

**Comment by ghost** [comment]
Ready for review in [Notion](https://www.notion.so/civicsoftware/OAE-social-sharing-65564388b6b049a7a8f80168cd0807ac#93d8d6bcd52b4d16a348588b9b450cb8). Handing off to @jaronheard for QA

**Comment by jaronheard** [comment]
@Dianna I've got an initial implementation of rich sharing previews good to go -- and they look good!

However, doing to incorporate dynamic content into Open Graph requires server-side rendering, which I think is a bridge too far for this initial launch, so I think that I'll put that on hold for now. We can try to incorporate some dynamic content into the content of the social posts instead.
