### ISSUE TITLE
Add actions for each of the api methods with a state update for Redux

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#230]
Add actions and redux state updates for each of the api routes in app/src/api/api

**Comment by iankerriganharris** [comment]
- [ ] Login
- [ ] Me
- [ ] Redeem invite
- [ ] Invite user gov
- [ ] Invite user campaign
- [ ] Resend invite
- [ ] Get gov users
- [ ] Get campaign users
- [ ] Send pw reset email
- [ ] Reset pw
- [ ] Update pw
- [ ] Get campaign activities
- [ ] Get gov activities
- [ ] Get campaigns for gov
- [ ] Create campaign for gov
