### ISSUE TITLE
Module 5: Reporting & Auditing

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#266]
Please create high fidelity mockups of:

- [x] Campaign's dashboard (summaries of status, labels, activity feed)
- [x] Government's dashboard (summaries of status, labels, activity feed)
- [ ] Export abilities Expenditures and Contributions (can export as XLS or Orestar)
- [x] Labels - filtering on Expenditures and Contributions
- [x] Labels - group applying on Expenditures and Contributions
- [x] Labels - removing/adding on record
- [x] Labels - Managing labels
- [x] Campaigns - government admin's over view of campaigns

**Comment by amysantee** [comment]
@danmelton we're getting info on the status of these!
