### ISSUE TITLE
API: Add a convert to orestar xml ability

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#284]
Create an ability to convert a contribution to Orestars xml.

Notes from conversation with Seth:

dont use a version header for xml submission to orestar

http://swoolley.org/files/s4pm-actblue.xml

use https://sos.oregon.gov/elections/Documents/xml_specs.pdf try to grab the schema for validations

oracle based processing/db/

xml version 1.0

no xml 

A maximum of 2,000 transactions and 2,000 contacts can be uploaded in a single XML file

contacts and transactions are separate uploads

contacts means address book in upload interface

issue where contacts that have already been submitted cant be submitted again....we need to figure out how to compare against previous downloads to see if the contacts has been uploaded already.

they do this for auto aggregation

**Comment by andrewbiang888** [comment]
Ok @danmelton , here are some snippets from our conversation yesterday so we can brainstorm next steps from here:

- we need to decompose this massive thing into a set of stories with testing for each layer
- we need an xml schema checking system that we can load the schema in for each field/type and then have a model function that converts the record into xml
- then check against that schema in our test suite
- then, we need to create a background function to do this that probably emails the user the result?

So I guess where do we go from here? 
 
Some initial questions I have:
1. Can we utilize existing api? I understand we need to submit transactions and contacts in xml, but can/should we reuse existing code that queries the db? I honestly don't know the api that well and can use some guidance 😅
2. Do we get to decide what transaction and contact IDs to use or does Orestar define that somewhere? We need to set a pattern if so.
3. Is there an option to do some test uploads to OreStar? I'd hate to put a lot of work into it and have it not work 🥴 I like to test-as-i-go.
4. I'd love to hear more about this "xml schema checking system." I'm thinking about getting a good json built and then use [xml-js](https://www.npmjs.com/package/xml-js) to convert it. So maybe we can use mocha to write json checking tests? You may have a grander idea of what this should manifest into so I'm happy for guidance!

**Comment by danmelton** [comment]
Great! We can write a small set of xml conversion helpers that takes a contribution or expenditure and creates an XML document out of it. This is where we need to do some massive testing.

- Can we utilize existing api?
Absolutely.

- Do we get to decide what transaction and contact IDs to use or does Orestar define that somewhere? We need to set a pattern if so.
Yes. I think we should use the matchId on contributions. Do expenditures need a contact id?

- Is there an option to do some test uploads to OreStar? I'd hate to put a lot of work into it and have it not work 🥴 I like to test-as-i-go.
No, not that I'm aware of.

- I'd love to hear more about this "xml schema checking system." I'm thinking about getting a good json built and then use xml-js to convert it. So maybe we can use mocha to write json checking tests? You may have a grander idea of what this should manifest into so I'm happy for guidance!

In, https://sos.oregon.gov/elections/Documents/xml_specs.pdf, each section has a chema for each field, i.e., here's the city:

```
 <xs:element name="city" minOccurs="0">
 <xs:annotation>
 <xs:documentation> </xs:documentation>
 </xs:annotation>
 <xs:simpleType>
 <xs:restriction base="xs:string">
 <xs:maxLength value="100"/>
 </xs:restriction>
 </xs:simpleType>
</xs:element>
```

which specifies the element 'city': 

```
<city>Portland</city>
```

We can load the schema into a validator and then pass the xml above to see if its correct. As long as it passes the schema validator, it should pass Orestar. 

**Stories**
- [ ] Your first task is to pull all the schemas out of that document, and consolidate into the top level items. I imagine there will be one for a contact and a transaction. There might be more. Create a schemas folder in the api/test/schemas, and place each one in there. You should attempt to validate the schemas as you go, using an online schema validator and seth's campaign finance data link above.

- [ ] Next, we need to create a conversion utility that converts a contribution or expenditure into the schema for a contact or a transaction. This should go into models/utils/ModelNameConverter.ts. Write a corresponding test for each file in test/converters/. Create one for a Contact, Contribution, and Expenditure.

- [ ] Next, we'll need to figure out how to do a bulk set of conversions. I think a service will be the best. Create a bulkOrestarExportService in both contributions and expenditures. It should probably take the same filter criteria as the getContrs or getExps, and get called in those functions similar to how csv and geojson are called as 'formats'. The format would be xml. Please add a test for this in test/services/expSer or contrServ.

- [ ] Hook that up to the getContr or get Exps service, if the format = xml. Update the format for GetExpendituresDto or GetContributionsDto in the controllers. 

- [ ] The frontend already has an api for this, we just need to update the redux ducks, 
```      if (contributionSearchAttrs.format === 'csv' && response.status === 200) {
        const contributions = await response.text();
        downloadFile(contributions, `contributions-download-${Date.now()}.csv`);
```
Add an xml format to ^

- [ ] Update the frontend export buttons to be dropdowns with two rows, one for csv and one for orestar.

**Comment by andrewbiang888** [comment]
Was able to do testing with Seth and have very similar solutions enabled. The contacts are not directly convertable (names for example) so they were kept isolated in Contribution vs Expenditure converters. Would love for the frontend to be updated and this could be more DRY.
