### ISSUE TITLE
Add New Campaign Flow

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#294]
This covers the complete feature flow to Add A New Campaign.

### Flow

- [ ] A government admin visits /campaigns
- [ ] No campaigns are present in the table, the table has a message, 'No Campaigns'
- [ ] They click 'Add a New Campaign'
- [ ] A modal pops up asking for campaign name, contact first, contact last, contact email address,
office sought dropdown with list of eligible offices:
Mayor 
Commissioner 1,
Commissioner 2
Commissioner 3
Auditor
- [ ] The submit button is disabled until a email, first and last name, campaign name, office sought, are all present, and email is valid. On blur of each field, if it has an error, the user is show an error in small red font.
- [ ] If they press submit, the modal calls a dispatch action, clears the data, hides
- [ ] If they press cancel, modal clears the data, hides
- [ ] The campaigns table has a new campaign with campaign name, first, last name and email

### Out of Scope
- navigation elements
- table columns manage button/actions, inkind or matched columns
- error state if the campaign had a problem being created (we'll add flash messaging later)
- success state that campaign was not created (we'll add flash messaging later)
- permissions that the current user can access the route or submit

### Images

/campaigns
<img width="1233" alt="▶_Iteration_5_-_civic__elections--ux_and_Routesadd_redux_action_C…" src="https://user-images.githubusercontent.com/99731/58766377-bbf89400-8532-11e9-8617-5ec97c0866a6.png">

/campaigns modal
<img width="565" alt="▶_Iteration_5_-_civic__elections--ux" src="https://user-images.githubusercontent.com/99731/58766409-0843d400-8533-11e9-90ad-23d952d84670.png">

/campaigns modal success - NOT DOING
<img width="557" alt="Screenshot_6_2_19__12_37_PM" src="https://user-images.githubusercontent.com/99731/58766789-b0f43280-8537-11e9-8408-2bc228a2d348.png">

### API Client

- getCampaignsAsync - gets a list of campaigns 
- createCampaignAsync - posts a campaign

### Redux

state.currentModal: enum AddNewCampaignModal
state.campaigns: an array of Campaigns {id, name, contact first/last, email }
state.errors: an array of errors [Error message]
state.flash: a flash message: string

**showModal**
type: SHOW_MODAL
modal: 'AddCampaign'
sets state.currentModal to AddCampaign

**dismissModal**
type: DISMISS_MODAL
unsets state.currentModal

**flashError**
type: FLASH_ERROR
errors: an array of javascript errors
sets state.errors

**flashSuccess**
type: FLASH_SUCCESS
message: 
sets state.flash

**CampaignsFetched**
type: CAMPAIGNS_FETCHED
campaigns: an array of campaigns
sets state.campaigns

**getCampaignsAsync**
Thunk action that:
```js
try {
const campaigns = await getCampaignsAsync
return dispatch CampaignsFetched(campaigns)
} catch (error) {
return dispatch applicationError([error])
}
```

**submitNewCampaignAsync**
Thunk action that:
```js
try {
await createCampaignAsync
dispatch submitNewCampaignSuccess
dispatch getCampaignsAsync
} catch (error) {
dispatch applicationError([error])
}
return dispatch dismissModal()
```

### Components

```
/components
--- /Campaigns
--- AddNewCampaignModal.js
--- CampaignsTable.js
/page
--- index.js - connected master component, 
--- CampaignsPage.js - layout component contains header, table, add button, modal
```

**AddNewCampaignModal.js**
takes props of currentModal, dismissModal, and submitNewCampaignAsync
Add validation for email, and make sure all fields are present
Disable submit button until present
Modal X in the upper right corner and the cancel both fire dismissModal
turn the modal off or on based on currentModal===AddNewCampaignModal

**CampaignsTable**
props: campaigns
Displays the campaigns table. If no campaigns, just display a message of 'No Campaigns'

**CampaignsPage.js**
takes props of currentModal, showModal, dismissModal, campaigns, submitNewCampaignAsync, getCampaignsAsync
componentDidMount, call getCampaignsAsync
pass currentModal, dismissModal, submitNewCampaignAsync to AddNewCampaignModal
Page contains: 
- Header
- Button with onpress event for showModal
- if no campaigns, display message with 'No Campaigns'
- Table with campaigns 

**index.js**
state props: currentModal, campaigns
dispatch props:  showModal, dismissModal, submitNewCampaignAsync, getCampaignsAsync

**Comment by jaronheard** [comment]
From Susan Mottet: Offices eligible this cycle are Mayor, Commissioner 1, and Commissioner 4. For future regular and special elections, add Commissioner 2, Commissioner 3, and Auditor.
