### ISSUE TITLE
Flash Message

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#295]
This covers the Flash message system for success and error states in the application

### Flow

- [ ] Any application action can be taken in redux that has an error or success state. The action updates a flash and/or errors in the state. The Flash message then appears. The user can dismiss if it there is an error, if no errors, the Flash message automatically dismisses in five seconds

### Out of Scope

- no out of scope

### Images

 - No images yet

### API Client

- none

### Redux

state.errors: an array of errors [Error message]
state.flash: a flash message: string

**dismissMessage**
type: DISMISS_FLASH
sets state.flash to null

**dismissErrors**
type: DISMISS_ERRORS
sets state.errors to[]

### Components

```
/components
--- /FlashMessage
--- index.js - redux connected component, 
--- FlashMessage.js - message format
```

**index.js**
dispatch props: dismissFlash, dismissErrors
props: flash, errors

**FlashMessage.js**
props dismissFlash(), dismissErrors(), flash"", errors[]
if errors is present, display flash message and a bulleted list of the error messages, the flash should have a red outline, and a light red background color.
if flash present, but not errors, display message, the component should have a darker green outline, and a light green background color.
Add an X in the upper right, that calls dimiss (which dismisses errors and flash)
If errors, add a button at the end of the message in the lower right quandrant that calls dismiss (which dismisses errors and flash)
on component did update:
- if flash message and no errors, set a this.timeOut that calls dismissFlash in 5 seconds
- if no flash, don't set the component to display none, clear the timeout, and set it to null

Add the FlashMessage to the Master Layout component

**Comment by andrewbiang888** [comment]
@jaronheard How do you feel about using Material UI for this? https://material-ui.com/components/snackbars/#snackbars

Happy to do vanilla too.

**Comment by jaronheard** [comment]
@andrewbiang888 let’s use Material!

**Comment by garretjames** [comment]
WIP: PR #350
