### ISSUE TITLE
Add Top Navigation Bar

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#300]
Add a top navigation bar

- [x] User can view a top navigation bar, click logo to go back to /dashboard if signed in, if not, sends them to /

### Out of Scope
- Links to About, Sandbox or Portal
- adding to layout, another story cover assembling the layout

### Images
<img width="1232" alt="Screenshot_6_3_19__8_34_AM" src="https://user-images.githubusercontent.com/99731/58814446-93c47000-85da-11e9-824f-f04f683a877b.png">

### Redux

state.me

```
openPage(page)
if (page is http) {
open(http) in a new window 
else {
dispatch(push(page))
}
dispatch({type: OPEN_PAGE, page})
```

### Components

```
./components
---/TopNavigation
------index.js - redux connector
------TopNavigation.js
```
**index.js**
- check state to see if the state.me is set

**TopNavigation.js**
dispatch props: openPage(page)
props: isSignedIn (bool)
- Logo is clickable, if isSignedIn, then call the props.openPage with '/dashboard/'
- else '/'
- design this component in storybook

**Comment by andrewbiang888** [comment]
@danmelton or @iankerriganharris  Could one of you elaborate on the `index.js - redux connector` is doing and maybe provide a basic example? I'm not familiar with this pattern and want to make sure I'm on the right track.
