### ISSUE TITLE
Design Update - 'Flash' Message

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#301]
We need to implement a general Flash message component to catch errors/successes.

Something ala:

![2011-08-29-flash-messages](https://user-images.githubusercontent.com/99731/58843867-43c0ca00-8629-11e9-8761-294570172115.png)

Any place where we have a success state in the design, we plan to replace with this flash message.

**Comment by amysantee** [comment]
@oovg will make a toast message example for error/success
