### ISSUE TITLE
User receive email to reset password [NEEDS WORK]

### ISSUE THREAD

**Issue by andrewbiang888** [hackoregon/openelections#319]
## Description
Assumes a user requested their password reset. This covers the email sent to the user

### Flow

- [ ] An email is sent to the user with a link to reset password

### Out of Scope
- requesting the reset

### Images
n/a

### API Client
Is Required? 👍

### Redux
Is Required? 👎

### Components
n/a

**Comment by danmelton** [comment]
we will tackle this one in the API
