### ISSUE TITLE
Add address line 2 to lookup

### ISSUE THREAD

**Issue by ggemelos** [hackoregon/openelections#328]
We currently do not make use of address line 2.  This appears to be an issue when the address is not standardized.  We should not see this on the input addresses which we be standardized, but we do see this on some of the voter registration addresses, a small percentage (~1k entries of 568k entries in Portland).  They are most likely get out the vote entries which do not go through the DMV's address standardization.

**Comment by ZhangWS** [comment]
Some of the Address 2 lines are plain wrong (e.g. includes city), but for now the sandbox branch incorporates an addr2 whenever it is not null.
