### ISSUE TITLE
Datascience/API Create 1000 unique address records for matching system

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#397]
We need about a 1000 unique records for Portland addresses with names to model the api/data science application integration.

Please create a csv file with made up names with actual addresses that we can load contributions into the api and load seed data into the dev db for the data science application.

It should match the table schama for datascience voter registration, and be a csv file.

**Comment by andrewbiang888** [comment]
May be helpful if we get the mentioned schema pasted in here for whoever can do this issue. I will try to hunt it down, but I'm not too familiar with where to find it.

**Comment by ZhangWS** [comment]
The Voter list has one schema, but our current running voter_db in docker reads it and has everything in a reduced format. What type of schema should the completed file follow?

**Comment by ZhangWS** [comment]
https://github.com/hackoregon/openelections/tree/ds-data-import/api/models/seeds
