### ISSUE TITLE
Swagger dependency fix

### ISSUE THREAD

**Issue by andrewbiang888** [hackoregon/openelections#403]
## Description

When PRs are being tested by TravisCI, the dependency of `swagger-ui-express` and `swagger-jsdoc`, `swagger-parser` is causing the tests to fail. A workaround or fix needs to be applied. 

Here is a log of the error: https://travis-ci.org/hackoregon/openelections/builds/558363544

### Steps to reproduce

Open a PR with this uncommented in `api/routes/index.ts`:
```js
    // app.use(
    //     '/api-docs',
    //     swaggerUI.serve,
    //     swaggerUI.setup(
    //         swaggerJSDoc({
    //             definition: {
    //                 openapi: '3.0.0',
    //                 info: {
    //                     title: 'Open Elections',
    //                     version: '1.0.0'
    //                 }
    //             },
    //             apis: ['routes/*']
    //         })
    //     )
    // );
```

### Expected result

The tests should pass without node_modules throwing errors.

### Actual result

`swagger-parser`, the node_module is killing the tests

**Comment by andrewbiang888** [comment]
The imports will need to be uncommented and they will need to be `npm install *` again as well.

**Comment by punkael** [comment]
Added a pull request to bring swagger back online.
