### ISSUE TITLE
Campaign name shows in side nav when logged in

### ISSUE THREAD

**Issue by gdoucette** [hackoregon/openelections#421]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by danmelton** [comment]
@billoosijok there is now a currentCampaignId under the state.campaigns key that you can use. If there isn't a campaign id, then also check to see if there is a government it, state.governments.currentGovernmentId, and show that name instead.

**Comment by billoosijok** [comment]
@danmelton Is there an endpoint to get campaign info using a campaignId?
