### ISSUE TITLE
Remove console logs from TopNavigation and ManagePortal

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#446]
![DevTools_-_qa_openelectionsportland_org_sign-in_and_openelections____code_openelections__-_____docker-compose_yml__openelections_](https://user-images.githubusercontent.com/99731/61580844-26f23000-aacb-11e9-841a-4268ec5cec30.png)

Also these:
    console.error node_modules/@emotion/cache/dist/cache.cjs.dev.js:268
      The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".
    console.log node_modules/@deck.gl/core/dist/es5/lib/init.js:43
      deck: deck.gl 6.4.10 - set deck.log.priority=1 (or higher) to trace attribute updates
    console.log node_modules/luma.gl/dist/es5/debug.js:17
      luma.gl: WebGL debug support imported

**Comment by kdv24** [comment]
I removed the console.logs from TopNavigation and Manage Portal, and addressed `console.error node_modules/@emotion/cache/dist/cache.cjs.dev.js:268
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".` by doing as it suggested and updating any instances to `:first-child to :first-of-type:`
I don't really understand the last two: 
`console.log node_modules/@deck.gl/core/dist/es5/lib/init.js:43
deck: deck.gl 6.4.10 - set deck.log.priority=1 (or higher) to trace attribute updates
console.log node_modules/luma.gl/dist/es5/debug.js:17
luma.gl: WebGL debug support imported` and I'm traveling so will be AFK again-  It would be great if someone else could finish this up!
