### ISSUE TITLE
Fix Invitation Flow - user sign up

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#449]
When the user access the /invitation?invitationCode=, 

- [ ] BUG one -> there is a brief flash of an error.

![Open_Elections](https://user-images.githubusercontent.com/99731/61581777-632b8d80-aad7-11e9-815f-d979c55f577f.png)

- [ ] Bug Two -> center the component
![Untitled](https://user-images.githubusercontent.com/99731/61581857-bb16c400-aad8-11e9-819c-1b472084702d.png)

- [ ] Bug Three -> navigate to sign in page on compelte

When I submit the passwords, and its a success navigate to the sign-in page

**Comment by jaronheard** [comment]
Fixed
