### ISSUE TITLE
Archive Contribution Button

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#505]
Create an archive contribution button component. It should be connected to state, and be passed a contributions id as ownProps.

Look at the state, and determine if the current user has permissions for the contribution. If not, don't render the button. 

If so, render the button, and hook up the archive contribution duct to it.
- only render the button if the contribution's state is DRAFT

**Comment by jasonvalenzuela** [comment]
@danmelton What behavior did we want after archiving a contribution?
