### ISSUE TITLE
TypeError: Cannot read property 'role' of undefined

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#527]
When I sign is as a campaign admin, and click manage portal, it doesn't load and complains about 'TypeError: Cannot read property 'role' of undefined'

![DevTools_-_qa_openelectionsportland_org_sign-in_and_Open_Elections](https://user-images.githubusercontent.com/99731/62094060-976a2100-b230-11e9-9386-5160acd09625.png)

**Comment by jaronheard** [comment]
Working in QA
