### ISSUE TITLE
Funky email wording in the invite email to new campaign 

### ISSUE THREAD

**Issue by amysantee** [hackoregon/openelections#533]
## Description

In the email that a person receives when the City adds a new Campaign, the text could use some work. It's based off of what the user puts into the form before hitting submit and the wording doesn't quite draw from that form correctly. This probably doesn't make sense so se below for steps to reproduce.

### Steps to reproduce

The form asks for the "Campaign Name" and let's say the person puts Amy Santee for President or just Amy Santee, and hits submit. The email they get says "You've been invited to join the Amy Santee" or You've been invited to join the Amy Santee for President" which does not make grammatical sense or read well.

### Expected result

It should say "You've been invited to join the Amy Santee for president campaign" (automatically put "campaign" on the end.) Yes this is nitpicky!

### Actual result

Does not say that!

### Environment

QA, Gmail

<img width="857" alt="Screen Shot 2019-07-29 at 6 50 45 PM" src="https://user-images.githubusercontent.com/48701371/62094577-786c8e80-b232-11e9-974c-eacb0a81098a.png">

<img width="867" alt="Screen Shot 2019-07-29 at 6 50 59 PM" src="https://user-images.githubusercontent.com/48701371/62094585-7c98ac00-b232-11e9-8ade-194802db7b0c.png">

<img width="314" alt="Screen Shot 2019-07-29 at 6 52 42 PM" src="https://user-images.githubusercontent.com/48701371/62094589-802c3300-b232-11e9-9951-84132c383264.png">

**Comment by kdv24** [comment]
this looks to me like it's already been re-worded, so closing now
