### ISSUE TITLE
Install gdal-bin to have access to geospatial data libraries

### ISSUE THREAD

**Issue by ZhangWS** [hackoregon/openelections#537]
In order to seed city boundaries table (currently city_limits), need to install gdal-bin to have access to ogr2ogr to import into post gis.

run to install:
apt-get update
apt-get install gdal-bin

original command, settings may need to be modified:
ogr2ogr -f "PostgreSQL" PG:"host=localhost user=postgres password=password dbname=open_elections_dev "api/models/seeds/geometry/cty_line.shp" -lco GEOMETRY_NAME=the_geom -lco FID=gid -nlt PROMOTE_TO_MULTI -nln city_limits -overwrite

**Comment by jaronheard** [comment]
@ZhangWS is this issue still open? Can you close it if it's done?
