### ISSUE TITLE
When I remove a user as a new campaign admin in a new campaign, i get an error

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#570]
Please fix this with a hotfix/name-GH-# off of master

Steps to Repro:

1. Create a new campaign
2. Sign in as the new campaign admin
3. Add a new user
4. Refresh the page
5. Manage the new user
6. Attempt to remove the user:

![Cursor_and_Open_Elections](https://user-images.githubusercontent.com/99731/62505876-3227aa00-b7b3-11e9-9bfa-1a58d093dd28.png)

**Comment by danmelton** [comment]
It could be a result of signing in multiple accounts and not cleaning up the state. Try signing into chrome incognito mode with the new campaign admin account and check.

**Comment by punkael** [comment]
Error Returns: User must be an admin
Found the problem the fixed on this pull https://github.com/hackoregon/openelections/pull/579

**Comment by danmelton** [comment]
@punkael great catch, thank you
