### ISSUE TITLE
Mod 4 - Expenditures Table View

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#572]
![civic__elections--ux](https://user-images.githubusercontent.com/99731/62508490-aa469d80-b7bc-11e9-8c6e-5d9a1fe00122.png)

### Description
Campaign Admin or Staff User is logged in, clicks on “Expenses” in side nav, lands on Expenses page w/ table view (3.0.0.0_Expenses in figma)

Page items:
- [x] Page Header with 'Expenses'
- [x] Table has a total number of expenditures in the upper left above it
- [x] Add New Expense button takes you to /expenses/new

User can see table of Expenditures with the following columns:
- [x] Transaction Date - which comes from the 3.1.0.0_Expenses_New card on figma, “Date of Expenditure”.
- [x] Payee - which comes from the 3.1.0.0_Expenses_New card on figma,  “Payee Name”. 
- [x] Amount - which comes from the 3.1.0.0_Expenses_New card on figma, “Amount”.
- [x] Payment - which comes from the 3.1.0.0_Expenses_New card on figma “Payment Method”.
- [x]  One column without a heading that has a view button for each expense. This button can take the user to view the full details of this expense.

### Out of Scope
- No labels
- No check boxes
- No filters, done in another story
- No bulk import/export button

**Comment by punkael** [comment]
Did not see "Payment Method" -ish field in the returned fields. Currently using "type".

Fields being returned:
```
address1, address2, amount, checkNumber, city, createdAt, date, description, id
name, payeeType, state, status, subType, type, updatedAt, zip
```
