### ISSUE TITLE
Mod - 4 expenditures showpage : expenditures/:id 

### ISSUE THREAD

**Issue by hayesmit** [hackoregon/openelections#574]
![civic__elections--ux](https://user-images.githubusercontent.com/99731/62509376-c8fa6380-b7bf-11e9-87da-4b953fad14ec.png)

- [x] Create a route for react router of expenditures/:id
- [x]  ID is the header
- [x] Campaign name and last updated at are present under ID header
- [x] Basics - Amount, Date of Expenditure, Type of Expenditure, Subtype of Expenditure, Payment Method and Check Number, Payee Information - Payee Type, Payee Name, Street, Address/PO Box, Street Address Line 2, Country/Region, City, State, Zip and County (Country/Region and County are not is the returned fields )
- [x] Other Details - Purpose of Expenditure and Notes
- [x] Back button arrow takes you back to expenses

### Out of Scope
- Labels, done in another story
- Jump to Activity, done in another story
- Edit and Submit buttons, done in another story

**Comment by punkael** [comment]
Basics Section has all but Country/Region and County. These fields are not returned by API
