### ISSUE TITLE
Mod 3: Match Strength Selector Widget

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#612]
Blocked until #615 #614 are done

Create a widget that enables a govadmin to see the match strength of a contributor:

![civic__elections--ux](https://user-images.githubusercontent.com/99731/62837560-a89a3100-bc25-11e9-94b1-3c3b659a66c6.png)

- [x] As a gov admin, when i see a contributor detail page contributions/:id, I can see the match strength symbol and text next to the Contributor title IF the type if INDIVIDUAL. Do not show the symbol or text for any other contributor type.

- [ ] On componentDidMount, fetch the match information for this contributionId using the getMatches duck 

- [x] If I click on the match strength text or symbol, AND the matchId field is set on the  contribution record, then I should see a pop up with the match details:

- [x] In the case of  strong match, I should see:

![civic__elections--ux](https://user-images.githubusercontent.com/99731/62837606-2eb67780-bc26-11e9-9503-672e82f4af91.png)

- [x] In the case of a weak match, I should see:

![civic__elections--ux](https://user-images.githubusercontent.com/99731/62837619-44c43800-bc26-11e9-808f-8de387fce7c9.png)

- [x] In the case of exact match, I should see:
![civic__elections--ux](https://user-images.githubusercontent.com/99731/62837626-5f96ac80-bc26-11e9-99f9-49f7ebab91e7.png)

- [x] In the case of none match, I should see:

![civic__elections--ux](https://user-images.githubusercontent.com/99731/62837644-7a692100-bc26-11e9-9d87-438b96cab3c0.png)

- [x] If no matchId is present, then the city user can select a record from the strong or weak matches. Inside the match object, results has an array type for exact, weak , strong, and an id for none. If the matchStrength is strong, then retrieve each of the results in the strong array, and display them one an a time in the modal. The last entry of the modal should be 'No matches'

- [x] When the user presses accept, post that information (contributionId, matchResult strength and id) to the update match result duct. If the user selects none, update the matchResultStrength to None and post the id.

![civic__elections--ux](https://user-images.githubusercontent.com/99731/62837700-480bf380-bc27-11e9-98ab-c5b1d10827fd.png)

- [x] Add an X to close the modal with no action.

- [x] Previous and Next should only appear if there is a previous and next

- [x] Show whether the address is in Portland or not. This one is weird! We need a small text display under the address for the user, that says: Address in Portland (green color) OR Address NOT in Portland (red color). This happens when the address for the user says portland, but, actually, they are not technically portland residents. Their address is serviced by Portland, but, they vote in another city. You will use the inPortland of the match result

**Comment by punkael** [comment]
@danmelton 
Does the match strength process only happen for contributions that are submitted for match? 

Should this logic:
Show match strength symbol if the user is gov admin && contributor type is INDIVIDUAL

Be this logic:
Show match strength symbol if the logged in user is gov admin, and contributor type is INDIVIDUAL or FAMILY, and submitted for contribution is YES?

**Comment by kdv24** [comment]
@punkael - styling for the widget is here: https://github.com/hackoregon/openelections/pull/818

**Comment by punkael** [comment]
Last bits will pull in with #888
