### ISSUE TITLE
Add the ability to update matchAmount by govAdmin

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#620]
- [x] If the user is a govadmin, the contribution type is individual, the status is not processed, draft or archived, compliant is not false and the submitForMatch is true, then allow the govAdmin user to select matcheable and pop up a modal for the match amount.

- [x] The drop down should have 'Match Contribution'
- [x] a Modal pops up, with match amount
- [x] populate the input with the donation amount (up to $50)
- [x] apply an input currency mask (top level is 50, no negative numbers)
- [x] Submitting the match uses the updateContribution duck, setting status to processed, compliant to true and matchAmount to the matchAmount
- [ ] Modal: hitting enter submits

![civic__elections--ux](https://user-images.githubusercontent.com/99731/62838562-fcf7dd80-bc32-11e9-83b7-8da9a9a66bd2.png)

![civic__elections--ux](https://user-images.githubusercontent.com/99731/62838581-421c0f80-bc33-11e9-9c68-6e1e419b73c3.png)

**Comment by kdv24** [comment]
The match is submitting without error, but when I look in the redux, `matchAmount` is null.  I’m obviously not passing something correctly, but correctly enough to not fail. If `matchAmount` is _not_ null, it fails with [object Object].
