### ISSUE TITLE
Mod 3 - Update the status of a contribution

### ISSUE THREAD

**Issue by gdoucette** [hackoregon/openelections#621]
![figma_contribution](https://user-images.githubusercontent.com/43457354/63307831-b9d9e200-c2a4-11e9-94b4-c25a3ea972cf.PNG)

**Description** Campaign Admin or Staff User is logged in, clicks on "Contributions" in side nave, lands on Contributions page with table view (7.0.0.0_Contributions_open in figma). User locates the Contribution they wish to update the status of and clicks the "view" button in that Contributions' row which takes you to the contribution page (7.1.0.0_Contribution in figma).

reference for status options: https://docs.google.com/document/d/1qmxZop4u9IE-pyBgxDEPW3WSfaJMY74XafgTjw-Nvv8/edit

Page items:

- [x] Page Header with 'Contribution id number 
- [x] Below Header has the "(name of the campaign)" | "Last edited (date and time this transaction was lasted edited)"
- [x] The current status of the transaction is displayed at the top of the transaction
- [x] A drop down Menu to change the Status of the transaction with 
-[ ]
-[ ]

not finished

**Comment by kdv24** [comment]
@danmelton or @gdoucette, just to be clear - is the dropdown with all the statuses (archived, draft, processed, submitted, out of compliance, and in compliance) always visible for gov Admin, and just has an additional option of Match Contribution in the specific scenario in #620.  And, are those the correct statuses?  Do we want the compliance modal for this as well?
