### ISSUE TITLE
Input error if Payment Method is "check"

### ISSUE THREAD

**Issue by kdv24** [hackoregon/openelections#636]
## Description
When "Check" is selected as the Payment Method, the error below appears. 

### Screen Shots
<img width="1281" alt="Screen Shot 2019-08-13 at 6 54 15 AM" src="https://user-images.githubusercontent.com/6107653/62947500-7c062680-bd97-11e9-8174-83100b030e65.png">

### Steps to reproduce
Start to add a new contribution and select "Check" as the Payment Method. 

### Expected result
The field for a check number should appear without a console error.

### Actual result
The above pictured error appears.

### Environment
Showing up in chrome, OS 10.14.5

**Comment by jaronheard** [comment]
#637 addressed
