### ISSUE TITLE
Employer Questions

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#639]
We need to update the employer questions section:

![Open_Elections](https://user-images.githubusercontent.com/99731/62958431-8a5e3d80-bdab-11e9-95c1-ac286247b47e.png)

- [x] Separate employer section from contributor section with more vertical space 
- [x] Only show Employer section if the contributor type is Individual OR Family
- [x] If the occupation letter date (currently commented out) is filled in, then the employer name, city, state and zip code are not required
- [x] If the self-employed option if selected, then the employer name, city, state and zip code are not required
- [x] Do not pre-fill in employer state, city or zipcode

**Comment by kdv24** [comment]
```
If the occupation letter date (currently commented out) is filled in, then the employer name,
city, state and zip code are not required

If the self-employed option if selected, then the employer name, city, state and zip code 
are not required
```
@danmelton just to clarify- we still want the employer fields to show, but not be required? Or do we want them not to be there at all?

**Comment by danmelton** [comment]
@kdv24 right, show the fields, but they aren't required
