### ISSUE TITLE
Auto set submit for match if type isnt contribution, subtype cash and contributor type individual or famil

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#646]
![Open_Elections](https://user-images.githubusercontent.com/99731/62960276-2d648680-bdaf-11e9-8e05-4c1da9b98f0a.png)

We need to set submitForMatch to no if type isnt contribution, subtype cash and contributor type individual or famil

**Comment by kdv24** [comment]
Looks good! Checked on other options and all default to no except those indicated above.
