### ISSUE TITLE
Improve prettier configuration for app

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/openelections#674]
## Description

We've got an `.prettierrc` file in the app that conflicts with our eslint configuration.

If you have the Prettier extension installed, and you use it to "Format document", it will apply the `.prettierrc` file rules, which conflict with the eslint rules.

A very clear example is with quotes. The .prettierrc file in /app has
`"singleQuote": false`, but our lint rules and .prettierrc

I'm not exactly sure how it's being used, but this is a clear indication that it's not being applied in the 

### Steps to reproduce

Use the Prettier extension in vscode to format document

### Expected result

Should be in sync with eslint rules

### Actual result

Many errors:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/7065695/63307456-5307f900-c2a3-11e9-8f85-dc01423068a0.png">

### Environment

Where are you seeing the error? 
(Environment details like your browser, operating system and is this local development)

**Comment by jaronheard** [comment]
In the meantime, run `ESLint: Fix all auto-fixable problems` instead.

**Comment by danmelton** [comment]
@jaron hiieee, please update the eslint config/prettier integration. I just got it werqing. Up to you all to make it a fun coding buddy.

**Comment by jaronheard** [comment]
Closed via #674
