### ISSUE TITLE
Add ability to sort & paginate contribution table results

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#678]
- [x] We need the ability to paginate the contributions table with live data from the api
- [x] We also need to be able to sort.

The api has the ability to do all of the above.

You look at the swagger endpoint OR services/contributions -> IGetContributionOptions for available options. 

```
sort?: {
        field: 'campaignId' | 'status' | 'date';
        direction: 'ASC' | 'DESC';
    };
```

Note the default sort is by updatedAt DESC, you don't have to specify that, the api does it automatically

**Comment by andrewbiang888** [comment]
@danmelton The current pagination is aware of the total # of contributions and breaks it into 50 per page. So at the bottom it says 50 of 70. If we want to rebuild the pagination feature, I'm okay with that. Is there a way to know the total # of hits with each request?
