### ISSUE TITLE
Add the ability to comment on an expenditure or contribution

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#686]
![civic__elections--ux](https://user-images.githubusercontent.com/99731/63443328-70df7600-c3e9-11e9-918d-b2d9a4f6e2f2.png)

Add the ability to comment on either a contribution or expenditure.

Use the postComment duck in either contributions or expenditures duck
Refresh the activity feed in the duck to see the comment

**Comment by kdv24** [comment]
Done, but included in #610
