### ISSUE TITLE
The Managing Campaign list manage button, loads Manage User form 

### ISSUE THREAD

**Issue by punkael** [hackoregon/openelections#713]
### Clicking the manage button on Managing Campaign list
![image](https://user-images.githubusercontent.com/964483/63952463-7e71ad00-ca34-11e9-9742-87bd5753837a.png)

### Opens
![image](https://user-images.githubusercontent.com/964483/63952018-a01e6480-ca33-11e9-9911-eff4a7819f1b.png)

The mange button should open a form to manage the campaign on the list or the button should be removed

**Comment by jaronheard** [comment]
For now, remove the manage button?

**Comment by kdv24** [comment]
Yep, this was actually covered in a different issue too - GH#823 GH#820
