### ISSUE TITLE
Mod 2 functionality bug - says all contributions are submitted when some are only drafts

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#716]
Description: When I saved a contribution as a draft and went back to the list of contributions, it said "2 submitted contributions" even though one was submitted and one was only saved as a draft. (Note: In the status line, it correctly labels the submitted one as submitted and the draft one as draft. It is just in the line above the list that says all are submitted.) 

![image](https://user-images.githubusercontent.com/48932344/64054117-6b490500-cb3a-11e9-884f-4915191ced91.png)

Steps to reproduce: Start at contribution list and note number of contributions in "X Submitted Contributions" line. Click "Add New Contribution." Enter info for a new contribution. Save as a draft. Go back to contribution list to look at number of contributions in "X Submitted Contributions" line. 

What should happen? I'm not sure what it should specifically say, but saying that all are submitted will confuse campaigns. I think this is just a language thing. It would be more clear if it said "2 Contributions Entered" or "2 Contributions Total." 

What happened. It says all entered contributions (saved as drafts and submitted) are submitted. 

Where are you seeing the error? I am in Chrome, signed in as a campaign (Hazel for Commissioner of Public Utilities).

**Comment by jaronheard** [comment]
Closed via #728

**Comment by jaronheard** [comment]
@susanmottet These fixes are on QA. Please review and reopen with additional detail if still not resolved.
