### ISSUE TITLE
Mod 2 functionality bug - when go back into saved draft, all entered info is gone

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#717]
## Description

When I enter a contribution and save it as a draft, then go back to the contribution list and click view to see it, it sometimes loads with none of the info entered into it. When I go back to the list, it is still on the list with the info correct in list view, so it still exists. But when I go in to view or submit it, it is sometimes (but not always) devoid of the information I entered. 

### Screen Shots

![image](https://user-images.githubusercontent.com/48932344/64054777-72254700-cb3d-11e9-9e2d-d9a4636262ae.png)

![image](https://user-images.githubusercontent.com/48932344/64054791-849f8080-cb3d-11e9-8908-8628f1674910.png)

### Steps to reproduce

Add a new contribution. Save as draft. Click "Contributions" to go back to list of contributions.  Click View to see recently entered contribution. Is the info you entered there? If so, try again. 

### Expected result

All info entered and saved should load when click to view it again. 

### Actual result

All info missing. 

### Environment

In Chrome. Logged in as Hazel for Commissioner of Public Utilities campaign.

**Comment by jaronheard** [comment]
@susanmottet These fixes are on QA. Please review and reopen with additional detail if still not resolved.
