### ISSUE TITLE
Mod 2 functionality bug - enter 08/05/2019 as contribution date, saves as 08/04/2019 (always one day prior)

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#718]
## Description

When I enter a contribution for a particular date, in this case, 08/05/2019, and save it as a draft, it always saves as the day prior (in this case, 08/04/2019). When I go to correct it, it saves again as the day prior. I think the only way to get it to save as the correct date, is to date it one day later and let it subtract a day when saving in order to save it as the right date. 

### Screen Shots

![image](https://user-images.githubusercontent.com/48932344/64054925-422a7380-cb3e-11e9-9859-b68da90e4060.png)

![image](https://user-images.githubusercontent.com/48932344/64054936-553d4380-cb3e-11e9-808d-c94186bfc033.png)

### Steps to reproduce

Add a new contribution and note what date you entered as the contribution date. Save as a draft. Go back to contributions list. Note what date it says on the contributions list. 

### Expected result

You should see the date you entered. 

### Actual result

You will see the date of the day prior to the date you entered. (Note: At this point, if you click "View" to see it again, it lists the day prior in the date field, as if you entered it that way. You can correct it, but when you save it, it goes back to the prior date. 

### Environment

I am in Chrome, signed in as the Hazel for Commissioner of Public Utilities.

**Comment by punkael** [comment]
Needs time zone added.

**Comment by jaronheard** [comment]
@susanmottet These fixes are on QA. Please review and reopen with additional detail if still not resolved.
