### ISSUE TITLE
API: acitvity records only should post for fields that have changed

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#737]
The API is posting activity records for fields that are not changing:

```"Campaign Admin updated contribution 1 fields. city changed from PORTLAND to PORTLAND. firstName changed from MICHAEL to MICHAEL. middleInitial changed from  to . lastName changed from STEPHANIE to STEPHANIE. name changed from null to null. state changed from OR to OR. occupation changed from Other to Other. employerName changed from  to . employerCity changed from  to . employerState changed from  to . checkNumber changed from  to . contributorType changed from individual to individual. subType changed from cash to cash. type changed from contribution to contribution. inKindType changed from null to null. oaeType changed from allowable to allowable. address1 changed from 838 SW 1ST AVE APT 300 to 838 SW 1ST AVE APT 300. address2 changed from  to . email changed from  to . phone changed from  to . phoneType changed from null to null. amount changed from 445.48 to 445.48. zip changed from 97204 to 97204. inKindDescription changed from  to . submitForMatch changed from false to false. paymentMethod changed from credit_card_online to credit_card_online. notes changed from  to . status changed from Draft to Draft."```

**Comment by punkael** [comment]
@danmelton We are sending in a complete record on updates. Created a ticket to fix on frontend:
Update only fields that have changed #750
