### ISSUE TITLE
Mod 2 - Enable campaigns to archive submitted contributions

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#742]
At present, a campaign can archive a draft contribution, which is good:
![image](https://user-images.githubusercontent.com/48932344/64307339-9cff0900-cf4a-11e9-8b80-9605d5e848f3.png)

But after a campaign submits a contribution, archiving it is no longer an option, which is bad: 
![image](https://user-images.githubusercontent.com/48932344/64307370-ba33d780-cf4a-11e9-8b36-891063af2ac1.png)

A campaign should be able to archive a submitted contribution, as well as a draft contribution.

**Comment by punkael** [comment]
@danmelton @susanmottet Does this break the process? If the status can be moved to archive, it can be moved to draft, edited, then and back to summited.
