### ISSUE TITLE
Remove - Submit for Match dropdown from Contribution Form

### ISSUE THREAD

**Issue by gdoucette** [hackoregon/openelections#743]
Remove - Submit for Match dropdown from Campaign Contribution Form

Per Susan from City - If campaign selects OAE Contribution Type = Matchable it will be automatically submitted for match. All other selections in OAE Contribution Type will not be submitted for matching.

**Comment by kdv24** [comment]
@gdoucette just to be clear... so is this simply removing that field (dropdown box) completely?
It seems to me the logic around contributions not being matchable if they're over 500 should still be included here. Is that true? If so, do we just want a flash message alerting the user in that scenario?

**Comment by kdv24** [comment]
ok. Based on slack conversation...
```
Me:  
Regarding the removal of the matchable dropdown for contributions…
It seems to me the logic around contributions not being matchable if they’re over 500 should still be included here. Is that true? If so, do we just want a flash message alerting the user in that scenario?

Dan Melton 11:38 AM:
not at the moment
they are trained on program rules
so, let's just remove the logic 
```
this should be good to merge in @punkael or @danmelton
