### ISSUE TITLE
Sign In component

### ISSUE THREAD

**Issue by andrewbiang888** [hackoregon/openelections#78]
- [x] frontend form
- [x] frontend form verification
- [x] Forgot Passowrd (forward to different component)

Validation:
-  at least 6 characters
- can't be `password`

Super Admin should have a harder password.

![Screen Shot 2019-04-15 at 7 56 14 PM](https://user-images.githubusercontent.com/20327807/56178863-9f22f400-5fb8-11e9-8465-8b65c42ad363.png)

**Comment by andrewbiang888** [comment]
The route for this component should `/signin`

**Comment by jaronheard** [comment]
What about using something like this to check password strength: https://github.com/dropbox/zxcvbn

**Comment by jaronheard** [comment]
Actually, looks like the thing I suggested is potentially heavyweight
