### ISSUE TITLE
Mod 4 - Enter expenses - can't see "status" in list view

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#784]
When viewing expenses entered, can't see "status," so campaigns don't know if an expense is in draft form or submitted.

![image](https://user-images.githubusercontent.com/48932344/64566897-de593500-d30b-11e9-857b-b2641b4a167c.png)

Log in as campaign. Go to "expenses." See that "status" is not a category in list view as it is for contributions. 

Should see status as a category and see if they are draft or submitted. 

Can't see status as a category.

Logged in as campaign in Chrome.

**Comment by danmelton** [comment]
@punkael could you triage?
