### ISSUE TITLE
Mod 4 - Expenses - Check # disappears after saving as draft

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#786]
After entering campaign expense and saving as draft, check # disappears.

![image](https://user-images.githubusercontent.com/48932344/64567621-815e7e80-d30d-11e9-93d4-068d3de258c2.png)

Log in as a campaign. Enter a new expense with check as payment method. Enter check #. Save as draft. Go to expenses list. Click View. Note that check # disappeared, therefore can't submit because check # is required. 

Expected that check # would be saved. 

Instead, check # disappeared. Had to reenter in order to submit. 

Logged in as campaign in Chrome.

**Comment by danmelton** [comment]
@punkael could you triage?

**Comment by punkael** [comment]
@danmelton check number is sent but not stored in the DB. If it's added to the DB it is returned.
