### ISSUE TITLE
Contribution entered, shows in GUI view, when click "view" individual transaction, most info is gone

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#828]
I have been told by multiple campaign users that they enter a contribution and save it and it shows up fine in the GUI, but when they click "View" most of the data is gone. But when they go back to GUI it is still there. I can replicate this in the GovAdmin experience as well. But, it is spotty. The same transaction will load with most data gone, and then reload with the data present. 

GUI View:
![image](https://user-images.githubusercontent.com/48932344/64911741-71161d00-d6da-11e9-94a8-034dfc10d61c.png)

View of individual contribution (I had to add an image of a different contribution than above because when I tried to replicate the experience to take a screen shot, it worked correctly. This bug has excellent self-preservational instincts.): 
![image](https://user-images.githubusercontent.com/48932344/64911762-a4f14280-d6da-11e9-9d15-3549960b6fa5.png)

Pick a contribution to view individually. Click View. Is all the data there? If so, try anther one. It is pretty prevalent, so picking at random is an effective strategy. 

This happens in Chrome, signed in as Campaign Admin or as Gov Admin.

**One of our users is a software engineer, and this is what he had to say:** 
_I've tried firefox and safari, and the same issue with data not loading into the gui happens.  They can submit all the drafts with:

update Contribution set status = "Submitted" where status = "Draft" and (campaignId = 8 or campaignId = 4) and governmentId = 1;
(8 is sarah, 4 is me).

But I found a potential reason for the error.

The broken pagination and the fact that the filter fails to persist leads to the problem.  The pages that don't load are the ones that don't load in the first 50 items.  Increasing the number, adding a filter, etc. make me not able to click to view it (the view page loads and the data is empty).  But the funny thing is sometimes if I click refresh a few times the data will load.  There's something strange going on where data is being filtered.

When looking at the network calls in the web developer tool in firefox I see there is some loading of the search results page even when the single contribution view page is loaded (there are two queries for contribution data, one for the single id, and one for the old search results).  There is a network race condition going on where the search result clears the data for the single call because the single call responds faster and thus is before the search results come in (being a slower call).

When I block the /contribution endpoint post request method in the firefox network analyzer, the view and submit works, but then I have to unblock it, refresh, filter to draft, reblock, click view, click submit.

7 steps to get around the race condition.

If they fix the persistence of the filter and the pagination, the missing data problem will solve itself as the race condition will reset the data but the search results will always have what you click on for view.

It's mainly because they reuse the internal table for contributions for singleton contributions and a search result list of contributions.  It's not an inherently bad design, but it can lead to a race condition like this._

**Comment by punkael** [comment]
Closes with #792
