### ISSUE TITLE
Manage Portal Page Layout

### ISSUE THREAD

**Issue by andrewbiang888** [hackoregon/openelections#83]
Route: `/manage`:

<img width="802" alt="Screen Shot 2019-05-13 at 5 04 46 PM" src="https://user-images.githubusercontent.com/20327807/57661804-3c198280-75a1-11e9-9db4-6cd66171b93c.png">

<img width="967" alt="Screen Shot 2019-04-15 at 8 05 14 PM" src="https://user-images.githubusercontent.com/20327807/56179273-d47c1180-5fb9-11e9-812f-b89bb42bcb96.png">

**Comment by danmelton** [comment]
reworking frontend components from ven's hi-fi designs. closing a bunch of issues to refocus us.
