### ISSUE TITLE
Sometimes legit email isn't recognized - can't login, can't change password

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#830]
## Description
Sometimes when you try to login, you can't with the correct email and password. And if you go to change your password, it doesn't recognize your email. A campaign user reported this to me but I wasn't sure it wasn't user error until it happened to my campaign test account and I double/triple/quadruple checked that the email I typed matches what is in the system. 

### Screen Shots (1: email not found; 2: unless I am not seeing something, that email is in the system as written)
![image](https://user-images.githubusercontent.com/48932344/64912913-07ead580-d6eb-11e9-9de0-3b37a36a9a1e.png)

![image](https://user-images.githubusercontent.com/48932344/64912916-1b963c00-d6eb-11e9-9af5-c27c3572a10c.png)

### Steps to reproduce

Go ahead and try to get a new password for susan.mottet+9@gmail.com. Does it give you an error? 

### Expected result

It generates an email to change passwords

### Actual result

It says email not found. 

### Environment

Where are you seeing the error? 
Chrome, trying to sign in as campaign.

**Comment by punkael** [comment]
Cannot reproduce. Used a gmail account like some.Account+9@gmail.com,
Was able to request a password and password request was received
