### ISSUE TITLE
Campaigns are reporting that the button to create a new user on their "Manage Portal" section isn't there.

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#831]
### Description

Campaigns are reporting that the button to create a new user on their "Manage Portal" section isn't there.

### Screen Shots

I can't replicate this one as a govadmin and I'm having trouble getting into my test campaign account. 

### Steps to reproduce

Sign in as campaign. Go to Manage Portal. Is the Add New User button there? 

### Expected result

Button should be there. Should enable you to go through protocol to add new user. 

### Actual result

Button not there.  

### Environment

Campaigns report seeing this when they are signed in.

**Comment by danmelton** [comment]
@susanmottet we'll need a little help replicating. could we get the email/information for the affected user? We could do a quick screen share.

**Comment by kdv24** [comment]
@susanmottet or @danmelton do we have any more info on this to replicate it?

**Comment by susanmottet** [comment]
I am unable to replicate it when I log on using my test campaign account.  Is there specific info I can ask the campaign who experienced it that would be helpful?

**Comment by kdv24** [comment]
Yeah, I also can't replicate it @susanmottet, so if you could find out specifics of the scenario when they experience this, that would be great.  Find out as much information as possible for us, such as: 
- browser, 
- computer (windows, mac, etc.), 
- role they are logged in as, 
- sequence of events they did leading up to it

... anything that could help us reproduce.  Thanks!
