### ISSUE TITLE
Ensure zip code in donor information is standard five digit

### ISSUE THREAD

**Issue by ggemelos** [hackoregon/openelections#838]
**Is your feature request related to a problem? Please describe.**
In the initial OAE transaction data, there are 18 transactions out of 987 where the donor zip code includes the plus four digits, e.g. xxxx-xxxx.  The matching code expects the zip code to just be the standard five digits.  This results in low similarity score for the zip code and a weak match.  

**Describe the solution you'd like**
We should ensure that the zip code field only contains the five digit zip code

**Comment by danmelton** [comment]
@kdv24 could we put an input mask on all zipcodes to be just 5?
