### ISSUE TITLE
Check donor names for invalid characters

### ISSUE THREAD

**Issue by ggemelos** [hackoregon/openelections#839]
**Is your feature request related to a problem? Please describe.**
In the initial OAE transaction data, we are seeing some names with invalid characters, e.g. M., John & Ruth, "JAMES " (has a space at the end).  This results in a low name similarity score and ultimately a weak match.    

**Describe the solution you'd like**
We should check for invalid characters in the name fields during data entry and not allow the campaign to enter invalid data.

**Comment by danmelton** [comment]
@punkael @kdv24 could we trim all fields that get submitted (remove space at beg and end of strings)
