### ISSUE TITLE
Misspelled addresses appearing in donor data

### ISSUE THREAD

**Issue by ggemelos** [hackoregon/openelections#840]
## Description
We are seeing some donor address data in the initial OAE transactions with misspelled street names, e.g. 9427 N CHARLOSTON AVE instead of 9427 N CHARLESTON AVE (transaction id 149).  I would think that the misspelled street name would be caught and fixed by the address standardization and lookup.  In this particular case, the donor address is decorated with the lat long which indicates the address standardization and lookup were run.

**Comment by danmelton** [comment]
@punkael could you take a look at this example with our google places lookup? Its in production...let's replicate on qa?

**Comment by punkael** [comment]
@danmelton 
It seems likely that this address was entered incorrectly. The autolookup currently allows the user to type in an address manually without picking an autofilled address. Looking into the exact above address:

When presented with the misspelled address:
9427 N CHARLOSTON AVE
Google places lookup produces this address:
9427 North Charleston Avenue

The geocoding api also matches the misspelled address to the correct address. So possibly the user entered the misspelled address and the geocoder returned the correct lat/lon anyway.

I could look into forcing the address to be picked from returned values?

**Comment by danmelton** [comment]
hrmm, kk, I don't want to force a match on the user....
