### ISSUE TITLE
Header in Firefox showing different "So and so for Mayor"

### ISSUE THREAD

**Issue by kdv24** [hackoregon/openelections#847]
## Description
In Firefox on a Mac, the dropdown menu when view is narrower, shows a different "... for Mayor" as shown in the picture below. The browser on the left in the picture is Safari- both are open to the same record.

### Screen Shots
![image](https://user-images.githubusercontent.com/6107653/65266984-fded1c00-dac8-11e9-9ea6-908a02182f21.png)

**Comment by danmelton** [comment]
are you signed in as the same user on both? which user? govadmin?

**Comment by kdv24** [comment]
Ahhh, no. GovAdmin on the left one and CampaignAdmin on the right. So, that's the Campaign Name at the top, but that campaign can still go in and see other Campaign's records.  Some of the roles are apparently still confusing to me.
