### ISSUE TITLE
Need to ask for 2 more pieces of info for one type of expense

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#859]
I just learned that when a campaign enters an expense that is a reimbursement for a personal expenditure, ORESTAR asks two additional questions that we don't collect. We ask payee (person getting reimbursed) and transaction date (date of the reimbursement). We need to also ask who the vendor was for the personal expenditure and the date of the personal expenditure.  

Phrased another way, if Daniel, a campaign staffer, spends their personal funds on a campaign expense at FedEx on 9/1 and the campaign reimburses them on 9/15, we need to collect:
1) Date of reimbursement (9/15) (we already ask this)
2) Date of original transaction (9/1)
3) Vendor for original purchase (FedEx) 
4) Payee, who was reimbursed (Daniel) (we already ask this)

If we don't add additional fields for this, when we build the bulk export to ORESTAR, this will create a problem. 

- [x] add to API, dateOriginalTransaction, vendorForOriginalPurchase
- [x] add to frontend, dateOriginalTransaction, vendorForOriginalPurchase

**Comment by punkael** [comment]
Expenditure form will not submit if it is not a personal expenditure. Modified validation to accept null on both dateOriginalTransaction and vendorForOriginalPurchase. Also convert date to microtime before evaluating to update record.
