### ISSUE TITLE
Mods 2 & 4: Bug when entering dates into search filter

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#875]
If you try to filter by date in the GUI, if you start by entering the month, then go to day, then go to year, things go wonky. Entering year tends to reset the month and day to “- -.” Then, when I type 2019 for year, it gets entered as 0019. To function in spite of this bug, I have to click on year first to enter 2019, which works. Then I go to month to enter a number like 08. Then I enter day. 

![image](https://user-images.githubusercontent.com/48932344/65806413-3aaaba00-e13e-11e9-9755-cc3c716d0f41.png)

**Comment by punkael** [comment]
Time is not required. Possibly the simple solution is to remove tabs and use two standard date fields stacked. The idea being that: 
- The standard date field does not have the problem.
- Both typing and mouse the date entry would be simplified.
