### ISSUE TITLE
Mods 2 & 4 - Campaign Name doesn't appear in individual transaction view

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#876]
When in transaction view, where it should say which campaign submitted the transaction, it just says “Campaign,” which I think was the placeholder. This way, I can’t see which campaign submitted the transaction when I am viewing it individually.

![image](https://user-images.githubusercontent.com/48932344/65806487-9e34e780-e13e-11e9-940d-48c43f4cbdd0.png)

**Comment by punkael** [comment]
@danmelton when logged in as govAdmin the campaign property is not returned on request for contributions by ID /contributions/:id. The same is true for expenditures.

**Comment by punkael** [comment]
pull #891 fixes this by pulling the campaign info from the list of contributions before updating state.

**Comment by punkael** [comment]
Return the campaign property to these endpoints (only missing when logged in as govAdmin):
GET /contributions/:id
GET /expenditures/:id

The campaign name will show up when these properties are there.
