### ISSUE TITLE
Mod 2 - Can we add "Awaiting Donor Response" do menu of actions City can take? 

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#879]
At present, for a matchable or qualifying contribution, I can select a number of actions to take on the transaction, like "match" or whatever.  I thought of another action I would like to be able to take: "awaiting donor response." This means I sent the donor a postcard and I need them to return it in order to deem it matchable. And campaigns would love to know which donors need to send postcards in in order to get matched. I wish I had thought of this idea before now!

**Comment by danmelton** [comment]
Can we user the comment feature for this?

**Comment by kdv24** [comment]
^ @danmelton is that a question for @susanmottet ?

**Comment by susanmottet** [comment]
If that is a question for me, I am not sure how to answer. I'm not sure how the comment feature would relate to my work flow in this situation. More clarity would be helpful.
