### ISSUE TITLE
User blocked from submitting expenses

### ISSUE THREAD

**Issue by amysantee** [hackoregon/openelections#886]
![Screen Shot 2019-09-30 at 9 02 55 AM](https://user-images.githubusercontent.com/48701371/65896160-930dd180-e361-11e9-99b5-5ad771e5cd0f.png)

User sees error message when she tries to submit expenses (when clicking submit).

Screen shot attached.

**Comment by punkael** [comment]
@danmelton pull #881 here fixes this
