### ISSUE TITLE
How to handle current record on view on Previous Donations

### ISSUE THREAD

**Issue by kdv24** [hackoregon/openelections#890]
This relates to #619 
As of now, the list of past contributions by a given donor includes all contributions, including the current contribution being viewed.  The concern is whether this might be confusing to the user.  The current record may not always be obvious when looking at the Previous Donations list.  

In this example, the current record is the only one listed in the 'Previous Donations.'
![image](https://user-images.githubusercontent.com/6107653/65975912-36bfb600-e424-11e9-9946-cf12bcffa83a.png)

Here, there are three Previous Donations listed, but no way to know one is the current record, or which record is the current one.
![image](https://user-images.githubusercontent.com/6107653/65976686-599e9a00-e425-11e9-8d77-62c7249c93a7.png)

Should we consider:

1. removing the current contribution from the `pastContributions` list,
2. changing the view to better indicate that one of the records is the one current being viewed (as well as maybe an alert message of some kind if they click it anyway?),
For example, the button for the current record has the word 'current', whereas the others say 'view.' Without this, there isn't a way to know which is which.  If the user goes ahead and clicks the 'current' button, a message pops up alerting them they are already viewing that record.
![image](https://user-images.githubusercontent.com/6107653/65976278-bfd6ed00-e424-11e9-9d73-217f7f1e6769.png)
3. other options?

@susanmottet I'd love your opinions on how to handle this best.

**Comment by susanmottet** [comment]
Option #2 would make it easiest to assess how all of the contributions together interact with program rules, so that one is the best option from my perspective. Thanks!

**Comment by kdv24** [comment]
Perfect! That's what's on QA right now @susanmottet.  And, actually I think it's slightly better on QA because the `Current` button is also disabled.
