### ISSUE TITLE
Don't grey out forms when they are disabled

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#893]
It's very hard to read the text for the city government.

**Comment by kdv24** [comment]
Currently the view is greyed out quite a bit, which I understand is too much, but without it greyed out at all, it's appears as though it's editable.  My suggestion is we change the opacity to 0.9, so it is more readable, but still gives the user a clue that it's disabled.  Examples of different opacity levels are below. 

Current:
![image](https://user-images.githubusercontent.com/6107653/66163129-7df4a500-e5e4-11e9-8c32-09acf72034d0.png)

This is at 0.8:
![image](https://user-images.githubusercontent.com/6107653/66163199-995fb000-e5e4-11e9-8951-1be62b8a9239.png)

This is at 0.9:
![image](https://user-images.githubusercontent.com/6107653/66163228-ac728000-e5e4-11e9-94f5-1d4526751b87.png)

And this is with no greying at all:
![image](https://user-images.githubusercontent.com/6107653/66163377-07a47280-e5e5-11e9-9fb0-cdb5bd3130dc.png)
