### ISSUE TITLE
Fix miscellaneous styling stuff

### ISSUE THREAD

**Issue by kdv24** [hackoregon/openelections#897]
I'm just going through the app repeatedly and looking for styling uglies.  At this point the big ones that keep bothering me are:

- [x] mismatch of button colors on tables
- [x] inconsistent vertical spacing of fields when adding a new contribution or expenditure
- [x] some fields only covering half the width when they are the only field in a row (also when adding a new contribution or expenditure)

I can add pictures for any of the above if you have questions.
Also, please add to the above checklist as you notice/know others @gdoucette and @amysantee

**Comment by kdv24** [comment]
addressed in PR #898

**Comment by kdv24** [comment]
I changed the button colors to be consistent, but I think it might be good if the `export` or `Add New Contribution` button was green or something that made it stand out from the others.  I realize it was different before I changed it, but I don't like the two shades of blue that make it look to me like we just didn't get it right.  Opinions? What would you like?

Here's what the table was:
![image](https://user-images.githubusercontent.com/6107653/66245252-7d7e0c00-e6c1-11e9-95c9-1d60518454b7.png)

And here's what is is now:
![image](https://user-images.githubusercontent.com/6107653/66245222-4f003100-e6c1-11e9-9f02-34a4a8cb72eb.png)

**Comment by kdv24** [comment]
Options: 
![image](https://user-images.githubusercontent.com/6107653/66245364-3e9c8600-e6c2-11e9-95c7-25ce9e8577ce.png)

![image](https://user-images.githubusercontent.com/6107653/66245542-5294b780-e6c3-11e9-8cf8-66a91b8bff1c.png)

**Comment by fstorr** [comment]
From an accessibility perspective, you you need to be hitting a color contrast ratio of at least 4.5:1 for most / all of the text on that page (but not the disabled-state "filter" button). I can't be completely sure as I've only got screen shots so can't see the size of the live text.

The green "add new expense" button looks to have a contrast of about 2.6:1 against its white text. If you want to keep the text white to match the other buttons, you'll need a more-contrasty green. This one works, if that's any good: `#008000`.

**Comment by kdv24** [comment]
Thanks for the feedback on accessibility @fstorr!  Here's what it looks like with that version.  Also, I can change other places we've used the previous green button, so they will use this new version. 
![image](https://user-images.githubusercontent.com/6107653/66323340-83016f00-e8d8-11e9-8ee5-730a3339d533.png)

**Comment by amysantee** [comment]
Thanks for this everyone!
