### ISSUE TITLE
incorrect time stamp for "last edited" on draft

### ISSUE THREAD

**Issue by amysantee** [hackoregon/openelections#913]
User went into a draft contribution and noticed that the "last updated" time stamp was several hours into the future. Need this to be accurate for record keeping and tracking purposes.
<img width="256" alt="Screen Shot 2019-10-08 at 2 26 40 PM" src="https://user-images.githubusercontent.com/48701371/66434667-ddcdc000-e9d7-11e9-94fd-cde8917bade2.png">

**Comment by kdv24** [comment]
@danmelton I'm not able to replicate this. @amysantee some additional information might make this easier to diagnose:
- is this error happening on every record they open or only certain ones? 
- is it always by the same amount?
- is there any chance timezones on the user's computer are different than Pacific Time?  

I'll also keep watching for it to see if I can find a point when it happens for me.

**Comment by amysantee** [comment]
Were you able to replicate? sorry I didn't respond sooner. If you want me to ask the user I can still do that.

**Comment by kdv24** [comment]
No @amysantee I've never been able to see it happen.
