### ISSUE TITLE
Add In Portland field to match results.

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#915]
The API returns whether or not an address is in portland as part of the match results.

Weirdly, an address can have Portland, OR but not actually be in portland!

Please add this information to our card widget

**Comment by punkael** [comment]
Currently it says "Address in Portland" in green when it is, and  Address Not in Portland in red when it's not. 

Here's an In Portland Address:
![image](https://user-images.githubusercontent.com/964483/66486850-36e13680-ea60-11e9-85dc-38e12567cd62.png)

**Comment by danmelton** [comment]
Oh, nice. In the case of the address not being 'in portland' AND its' an exact match, can we make the exact match red?

**Comment by punkael** [comment]
Like this
![image](https://user-images.githubusercontent.com/964483/66608751-28804100-eb6c-11e9-9487-3b7ece1491e9.png)
not real record, set inPortland to false to test

**Comment by punkael** [comment]
Pull #943
