### ISSUE TITLE
Mod 2 - Contributions - Can we add "OAE Type" to the GUI view? 

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#918]
I am noticing that I need "OAE Type" to be listed in GUI view for workflow purposes. Can we add that? If there isn't space, we could replace campaign name with campaign #. But if there is space, having both the name of the campaign and OAE Type would be nice.

**Comment by danmelton** [comment]
let's do it for both campaigns and government users.

**Comment by kdv24** [comment]
Is this referring to the view accessed through the `Campaigns` sidebar?

**Comment by kdv24** [comment]
@susanmottet @danmelton I'm not clear which view is the GUI you're referring to.  Is this referring to the view accessed through the `Campaigns` sidebar, and if so, isn't that only viewable by government users?

**Comment by danmelton** [comment]
This would be on the /contributions table view

**Comment by kdv24** [comment]
👍
