### ISSUE TITLE
Design changes for New Contribution UI

### ISSUE THREAD

**Issue by amysantee** [hackoregon/openelections#922]
Attached image has recommendations for New Contribution UI. Based on what is live today, we recommend:

- [x] Relabel "Save" to "Save Draft"
- [x] Relabel "Archive" to "Move to trash"

Here is a link to the campaign user research results and feedback for reference: https://docs.google.com/presentation/d/1wr6uWh6AqPyTTPRutvO90Sw_QwyE4yQdFMfP27CjPZw/edit#slide=id.p.

- [x] (On PR #920 ) Lastly, when entering text into the activity feed comment field, it's super tiny! Needs to be bigger so it's easily read before submitting. See attached screen shot.

![Screen Shot 2019-10-09 at 10 08 22 AM](https://user-images.githubusercontent.com/48701371/66503800-c0066680-ea7c-11e9-8442-10aa0b6bd76c.png)

![Screen Shot 2019-10-09 at 10 03 59 AM](https://user-images.githubusercontent.com/48701371/66503455-276fe680-ea7c-11e9-9f60-7f4d93603590.png)

- [x] Set initial value of city/state as Portland/OR

**Comment by amysantee** [comment]
@gdoucette FYI

**Comment by kdv24** [comment]
Text size on the message box was enlarged in another PR that should be pulled in today.

**Comment by kdv24** [comment]
@amysantee is this based on an older version than what's on QA now? The occupation and letter date are both in the contributor section already.  Also, I believe the tabbing has been updated. So, I'll wait to proceed until I hear input back on which tasks are for sure still remaining and what the decisions are on some of those listed in Recommendations.
