### ISSUE TITLE
Design changes for Contributions page UI (campaign portal)

### ISSUE THREAD

**Issue by amysantee** [hackoregon/openelections#923]
Recommendations to improve Contributions UI page:

- [x] Update Date column to be 'Contr Date'.
- [x] Update Amount to be Contr Amount
- [x] Add 'Matched' Column
- [x] Sort/filter should remain applied if a user goes to an individual contribution and then returns to this page.

Here is a link to the campaign user research results and feedback for reference: https://docs.google.com/presentation/d/1wr6uWh6AqPyTTPRutvO90Sw_QwyE4yQdFMfP27CjPZw/edit#slide=id.p.

![Screen Shot 2019-10-09 at 10 13 40 AM](https://user-images.githubusercontent.com/48701371/66504195-7ec28680-ea7d-11e9-8cf9-c98ea85e66fb.png)

**Comment by amysantee** [comment]
@gdoucette FYI

**Comment by kdv24** [comment]
Messaged @amysantee for clarity on "Matched" column contents. Waiting to proceed.

**Comment by kdv24** [comment]
Currently just blank if no match amount.  Is that what we want?

![image](https://user-images.githubusercontent.com/6107653/66941240-5990c380-effb-11e9-8c31-876ca3290fb6.png)
