### ISSUE TITLE
Design changes for Expenses page for campaigns

### ISSUE THREAD

**Issue by amysantee** [hackoregon/openelections#924]
Recommendations for the Expenses page for campaigns:

- [x] Date: not clear if this is the transaction date or submission date. Clarify the language and if possible create columns for both of these.
- [x] Sort/filter should remain applied if a user goes to an individual expense and then returns to this page.
- [x] Campaigns want to quickly know which category of expense each line item refers to. Create a column for this. E.g., office supplies, advertising, etc.)
- [x] Show payment type - could be useful for sorting by a certain payment type for situations where there is a question about an expense
- [x] Add a status field.

Here is a link to the campaign user research results and feedback for reference: https://docs.google.com/presentation/d/1wr6uWh6AqPyTTPRutvO90Sw_QwyE4yQdFMfP27CjPZw/edit#slide=id.p.

![Screen Shot 2019-10-09 at 10 45 05 AM](https://user-images.githubusercontent.com/48701371/66506298-eda1de80-ea81-11e9-9c3a-16a5d1984cdb.png)

**Comment by amysantee** [comment]
@gdoucette FYI

**Comment by kdv24** [comment]
@amysantee please let me know if I'm mistaken, butt I believe the third item listed, was decided not to be needed anymore, and the fourth and fifth items already exist in the UI:
![image](https://user-images.githubusercontent.com/6107653/66858568-656a8000-ef3e-11e9-899c-881fdd819cd6.png)

**Comment by kdv24** [comment]
@amysantee - 
Also, for the 'Date' column, I don't know what the user is putting in to the "Expenditure Date" column.   It currently displays what they fill in on the "Expenditure Date" from the individual view, but I'm not clear how the "Expenditure Date" differs from the "Original Transaction Date," or if the user is just putting in the current date for the 'Expenditure Date'.  Can you clarify how it's being used so I can clarify the text? 

![image](https://user-images.githubusercontent.com/6107653/66860170-7e286500-ef41-11e9-9e1f-07f2224fb09d.png)
