### ISSUE TITLE
Add OAE program branding to openelectionsportland.org

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#934]
One of the things that is in the contract but not the user design was adding the OAE program branding to the openelectionsportland.org site.  At the user design phase, we didn't have a logo yet. Now we do. Can we add it somewhere on the black stripe at the top:

![image](https://user-images.githubusercontent.com/48932344/66515004-20a09e00-ea93-11e9-8087-f00e2c0051e1.png)

I am attaching the logo file to use, but I have others if needed. 
![OAE Logo Cropped](https://user-images.githubusercontent.com/48932344/66515325-c0f6c280-ea93-11e9-99fe-f99ac5556ea7.jpg)

**Comment by danmelton** [comment]
let's replace the civic logo with the new flower logo (all white), and update the Open Elections text to be Open & Account Elections Portland.

Also update the email templates.

**Comment by kdv24** [comment]
Is something like this what you're thinking @danmelton / @susanmottet ?
![image](https://user-images.githubusercontent.com/6107653/66686708-2c2bca80-ec35-11e9-965f-e4705ea32845.png)

**Comment by susanmottet** [comment]
Looks good to me!

**Comment by danmelton** [comment]
hi hi, that takes up a lot of space...

Let's do the following:

1. Make the purple background green, following the logos color, for the header
2. Using just the flower, make a square icon, with a white background. Replace the civic square logo with the new square flower.
3. Replace Open Elections text in the header with Open & Accountable Elections Portland.
4. Update our email template to to reflect the same changes as above
