### ISSUE TITLE
In City view of individual contributions/expenses, allow City to change info campaigns entered into each field

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#937]
Part of the "god mode" we initially agreed to for the City is that the City can change the info campaigns enter for each transaction. So if they select OAE type as "matchable" the City can go in and change it to "allowable." Or if they chose 97201 as a zip code, the City can go in and change it to 97211. It looks like the City doesn't have the ability to change info in transactions that have been submitted. Can we fix that? It is helpful especially as a temporary workaround if something isn't functioning correctly.

**Comment by punkael** [comment]
Looking this over to determine steps to completion
