### ISSUE TITLE
Can't add new City User

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#973]
I have a new Deputy Director and I am having trouble setting him up in the OAE App as a new user for the City.  When I go to Manage Portal and select Add New User and add him, he gets an email to have him join the Galen for Mayor campaign, as opposed to being a City user. 

Even then, when he clicks on the link in the email, it just takes him to openelectionsportland.org/sign-in, not to the page where you create a password. So, he can't create a password and login to see if he is a City user or a campaign user. 

Anything you can do to help is appreciated. Thanks!

**Comment by danmelton** [comment]
It appears that when we attempt to add a new city user, it's using the campaign user form:

![Open_Elections](https://user-images.githubusercontent.com/99731/67529277-83d42800-f670-11e9-8781-80bbe7338989.png)

Let's update this to use an add new gov admin user form and make sure its sending the right params
