### ISSUE TITLE
Create Redux  Ducts and Selectors for Public Data Api

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#974]
Add a new duct with a key for 'publicData'

Redux State
```js 
{ 
 publicData: {
  filters: {
  office: null,
  campaignId: null,
  startDate: null
  endDate: null
 },
  rawData: [], // hydrated by GET_PUBLIC_CONTRIBUTIONS
  filtered: []  //any time a filter changes, rawData is used. No filter, its a copy of rawData?
}
```

- [x] Add a new Redux Action to get API Data and hydrate state
On app load, fire off GET_PUBLIC_CONTRIBUTIONS, add to state

- [ ] Add a new redux action to filter state based on filter params. Action Type - > FILTER_CONTRIBUTIONS

**Comment by DingoEatingFuzz** [comment]
Finished in #779
