### ISSUE TITLE
Add a Portland Map with Point data from contributions

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#975]
Portland Map - zooming will not trigger filters
-> dots per address
-> can we add a layer for portland neighborhoods?
-> add layers for age, race, income?

**Comment by DingoEatingFuzz** [comment]
An existing pattern from the Civic design system:

https://hackoregon.github.io/civic/?path=/story/component-lib-maps-map-overlay--example-choropleth-circle-map

**Comment by DingoEatingFuzz** [comment]
Finished in #779
