### ISSUE TITLE
Add a Donation Size by Range of Donation Pie Chart

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#977]
Donation Size by Total Amounts Pie Chart Visualization (Filter out OaeType of ‘public_matching_contribution’) - all contributions, excluding oae match
0 to 25 (micro donors)
25 to 100 (small donors)
100 to 250 (medium donors)
250 to 1000 (large donors)
Over 1000 (mega donors)

**Comment by DingoEatingFuzz** [comment]
Pie chart example from Civic design system: https://hackoregon.github.io/civic/?path=/story/component-lib-charts-pie-chart--standard

**Comment by DingoEatingFuzz** [comment]
Finished in #779
