### ISSUE TITLE
Create a table of campaigns with data for amount, total, matched, and donor sizes

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#980]
Table by Campaign Name - filter out oae public match type
Campaign Name, Total Amount, Total Donations, Total Match Amount, 
0 to 25 (micro donors)
25 to 100 (small donors)
100 to 250 (medium donors)
250 to 1000 (large donors)
Over 1000 (mega donors)

**Comment by DingoEatingFuzz** [comment]
Finished in #779
