### ISSUE TITLE
In a contribution or expenditure's Transaction History, it doesn't differentiate between Government Admin users

### ISSUE THREAD

**Issue by susanmottet** [hackoregon/openelections#990]
I went in as a new government admin user (First and Last Names: Hael Mottet) and edited a contribution. In the Transaction History log, it just says "Government Admin" updated contribution 1025 fields" as opposed to identifying which Government Admin (Hael Mottet) did it. We do need that in order to know who is doing what. If someone did something unauthorized or illegal or just wrong, we need to know who. 

![image](https://user-images.githubusercontent.com/48932344/68900038-d93bac00-06e7-11ea-8d18-f5c8bddbfa65.png)

**Comment by danmelton** [comment]
On QA, We just named that account Government Admin. So, it's Mrs. Government Admin, sorry confusing!
